In [2]:
import pandas as pd

In [3]:
df= pd.read_excel("financial_sample.xlsx")
df.head()

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,NaN,1618.5,3,20,32370.0,0.0,32370.0,16185.0,16185.0,2014-01-01,1,January,2014
1,Government,Germany,Carretera,NaN,1321.0,3,20,26420.0,0.0,26420.0,13210.0,13210.0,2014-01-01,1,January,2014
2,Midmarket,France,Carretera,NaN,2178.0,3,15,32670.0,0.0,32670.0,21780.0,10890.0,2014-06-01,6,June,2014
3,Midmarket,Germany,Carretera,NaN,888.0,3,15,13320.0,0.0,13320.0,8880.0,4440.0,2014-06-01,6,June,2014
4,Midmarket,Mexico,Carretera,NaN,2470.0,3,15,37050.0,0.0,37050.0,24700.0,12350.0,2014-06-01,6,June,2014

In [4]:
sa=df[['Manufacturing Price', 'Sale Price']]
sa1=sa.rename(columns={'Manufacturing Price': 'quantity','Sale Price': 'unit_price'})
sa1

     quantity  unit_price
0           3          20
1           3          20
2           3          15
3           3          15
4           3          15
..        ...         ...
695       260         300
696       260         300
697         5           7
698        10           7
699       250          12

[700 rows x 2 columns]

In [5]:
# date= df[['Month Number', 'Month Name', 'Year']]
# date1=date.rename(columns={'Month Number':'d_day','Month Name':'d_month','Year':'d_year'})
# date1
date=df[['Month Number', 'Month Name', 'Year']]
date1=date.rename(columns={'Month Number': 'd_day','Month Name': 'd_month','Year':'d_year'})
date1

     d_day   d_month  d_year
0        1   January    2014
1        1   January    2014
2        6      June    2014
3        6      June    2014
4        6      June    2014
..     ...       ...     ...
695      3     March    2014
696     10   October    2014
697      2  February    2014
698      4     April    2014
699      5       May    2014

[700 rows x 3 columns]

In [6]:
df1 = pd.read_excel("Electric_Vehicle_Population_Data.xlsx")
df1.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Base MSRP,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,5YJXCAE26J,Yakima,Yakima,WA,98908.0,2018,TESLA,MODEL X,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,238,0,14.0,141151601,POINT (-120.56916 46.58514),PACIFICORP,5.307700e+10
1,JHMZC5F37M,Kitsap,Poulsbo,WA,98370.0,2021,HONDA,CLARITY,Plug-in Hybrid Electric Vehicle (PHEV),Clean Alternative Fuel Vehicle Eligible,47,0,23.0,171566447,POINT (-122.64681 47.73689),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EB0K,King,Seattle,WA,98199.0,2019,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,220,0,36.0,9426525,POINT (-122.40092 47.65908),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,1N4AZ0CP5D,King,Seattle,WA,98119.0,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75,0,36.0,211807760,POINT (-122.3684 47.64586),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
4,5YJSA1E21H,Thurston,Lacey,WA,98516.0,2017,TESLA,MODEL S,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,210,0,22.0,185810306,POINT (-122.75379 47.06316),PUGET SOUND ENERGY INC,5.306701e+10

In [7]:
# product= df1[['Electric Vehicle Type', 'Model']]
# product1=product.rename(columns={'Electric Vehicle Type': 'Product_Name','Model': 'Category'})
# product1

In [8]:
customer=df[['Segment', 'Country']]
customer1=customer.rename(columns={'Segment':'customer_name','Country':'city'})
customer1

        customer_name                      city
0          Government                    Canada
1          Government                   Germany
2           Midmarket                    France
3           Midmarket                   Germany
4           Midmarket                    Mexico
..                ...                       ...
695    Small Business                    France
696    Small Business                    Mexico
697        Government                    Mexico
698        Government                    Canada
699  Channel Partners  United States of America

[700 rows x 2 columns]

In [9]:
!pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\tuyiz\anaconda3\lib\site-packages (9.2.0)

In [10]:
import mysql.connector 
mydb=mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales10"
)

In [11]:
cursor=mydb.cursor()

In [12]:
date1=date.fillna('')
date1

     Month Number Month Name  Year
0               1    January  2014
1               1    January  2014
2               6       June  2014
3               6       June  2014
4               6       June  2014
..            ...        ...   ...
695             3      March  2014
696            10    October  2014
697             2   February  2014
698             4      April  2014
699             5        May  2014

[700 rows x 3 columns]

In [13]:
datea=date.dropna()
datea

     Month Number Month Name  Year
0               1    January  2014
1               1    January  2014
2               6       June  2014
3               6       June  2014
4               6       June  2014
..            ...        ...   ...
695             3      March  2014
696            10    October  2014
697             2   February  2014
698             4      April  2014
699             5        May  2014

[700 rows x 3 columns]

In [14]:
insert_query = f"INSERT INTO customer_tb ({','.join(customer1.columns)}) VALUES ({','.join(['%s']*len(customer1.columns))})"
    
for _, row in customer1.iterrows():
    values = tuple(row)
    cursor.execute(insert_query, values)
    
mydb.commit()

In [15]:
insert_query = f"INSERT INTO date_tb ({','.join(date1.columns)}) VALUES ({','.join(['%s']*len(date1.columns))})"
    
for _, row in date1.iterrows():
    values = tuple(row)
    cursor.execute(insert_query, values)
    
mydb.commit()

ProgrammingError: 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'Number,Month Name,Year) VALUES (1,'January',2014)' at line 1

In [ ]:
insert_query = f"INSERT INTO product_tb ({','.join(product1.columns)}) VALUES ({','.join(['%s']*len(product1.columns))})"
    
for _, row in prodact1.iterrows():
    values = tuple(row)
    cursor.execute(insert_query, values)
    
mydb.commit()

In [ ]:
insert_query = f"INSERT INTO sale_tb ({','.join(sa1.columns)}) VALUES ({','.join(['%s']*len(sa1.columns))})"
    
for _, row in sa1.iterrows():
    values = tuple(row)
    cursor.execute(insert_query, values)
    
mydb.commit()