In [11]:
import pandas as pd
df=pd.read_csv('financial_sample.csv')
df

,Segment,Country,Product,Discount Band,Units Sold,Manufacturing Price,Sale Price,Gross Sales,Discounts,Sales,COGS,Profit,Date,Month Number,Month Name,Year
0,Government,Canada,Carretera,None,1618.5,$3.00,$20.00,"$32,370.00",$-,"$32,370.00","$16,185.00","$16,185.00",01/01/2014,1,January,2014
1,Government,Germany,Carretera,None,1321.0,$3.00,$20.00,"$26,420.00",$-,"$26,420.00","$13,210.00","$13,210.00",01/01/2014,1,January,2014
2,Midmarket,France,Carretera,None,2178.0,$3.00,$15.00,"$32,670.00",$-,"$32,670.00","$21,780.00","$10,890.00",01/06/2014,6,June,2014
3,Midmarket,Germany,Carretera,None,888.0,$3.00,$15.00,"$13,320.00",$-,"$13,320.00","$8,880.00","$4,440.00",01/06/2014,6,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,$3.00,$15.00,"$37,050.00",$-,"$37,050.00","$24,700.00","$12,350.00",01/06/2014,6,June,2014
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,$260.00,$300.00,"$742,500.00","$111,375.00","$631,125.00","$618,750.00","$12,375.00",01/03/2014,3,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,$260.00,$300.00,"$163,800.00","$24,570.00","$139,230.00","$136,500.00","$2,730.00",01/10/2014,10,October,2014
697,Government,Mexico,Montana,High,1368.0,$5.00,$7.00,"$9,576.00","$1,436.40","$8,139.60","$6,840.00","$1,299.60",01/02/2014,2,February,2014
698,Government,Canada,Paseo,High,723.0,$10.00,$7.00,"$5,061.00",$759.15,"$4,301.85","$3,615.00",$686.85,01/04/2014,4,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,$250.00,$12.00,"$21,672.00","$3,250.80","$18,421.20","$5,418.00","$13,003.20",01/05/2014,5,May,2014

In [12]:
df.columns = df.columns.str.strip().str.lower().str.replace(' ', '_')

# Print cleaned column names
print(df.columns)

Index(['segment', 'country', 'product', 'discount_band', 'units_sold',
       'manufacturing_price', 'sale_price', 'gross_sales', 'discounts',
       'sales', 'cogs', 'profit', 'date', 'month_number', 'month_name',
       'year'],
      dtype='object')

In [13]:

new_dataset = df[['segment','country','product', 'discount_band', 'units_sold','sale_price','sales','date','month_name', 'year']]
new_dataset.to_csv("new_dataset.csv", index=False)
new_dataset.head()

,segment,country,product,discount_band,units_sold,sale_price,sales,date,month_name,year
0,Government,Canada,Carretera,None,1618.5,$20.00,"$32,370.00",01/01/2014,January,2014
1,Government,Germany,Carretera,None,1321.0,$20.00,"$26,420.00",01/01/2014,January,2014
2,Midmarket,France,Carretera,None,2178.0,$15.00,"$32,670.00",01/06/2014,June,2014
3,Midmarket,Germany,Carretera,None,888.0,$15.00,"$13,320.00",01/06/2014,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,$15.00,"$37,050.00",01/06/2014,June,2014

In [14]:
df_renamed = new_dataset.rename(columns={
    "segment": "customer_name",
    "country": "city",
    "product": "product_name",
    "discount_band":"category",
    "units_sold":"quantity",
    "sale_price":"price",
    "sales":"total_sales",
    "month_name":"month"
    
})

# Display updated column names
print(df_renamed.columns)

Index(['customer_name', 'city', 'product_name', 'category', 'quantity',
       'price', 'total_sales', 'date', 'month', 'year'],
      dtype='object')

In [15]:
df_renamed

,customer_name,city,product_name,category,quantity,price,total_sales,date,month,year
0,Government,Canada,Carretera,None,1618.5,$20.00,"$32,370.00",01/01/2014,January,2014
1,Government,Germany,Carretera,None,1321.0,$20.00,"$26,420.00",01/01/2014,January,2014
2,Midmarket,France,Carretera,None,2178.0,$15.00,"$32,670.00",01/06/2014,June,2014
3,Midmarket,Germany,Carretera,None,888.0,$15.00,"$13,320.00",01/06/2014,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,$15.00,"$37,050.00",01/06/2014,June,2014
...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,$300.00,"$631,125.00",01/03/2014,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,$300.00,"$139,230.00",01/10/2014,October,2014
697,Government,Mexico,Montana,High,1368.0,$7.00,"$8,139.60",01/02/2014,February,2014
698,Government,Canada,Paseo,High,723.0,$7.00,"$4,301.85",01/04/2014,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,$12.00,"$18,421.20",01/05/2014,May,2014

In [16]:
df_renamed['price'] = df_renamed['price'].str.replace(r'\$', '', regex=True)
df_renamed['total_sales'] = df_renamed['total_sales'].str.replace(r'\$', '', regex=True)
df_renamed

,customer_name,city,product_name,category,quantity,price,total_sales,date,month,year
0,Government,Canada,Carretera,None,1618.5,20.00,"32,370.00",01/01/2014,January,2014
1,Government,Germany,Carretera,None,1321.0,20.00,"26,420.00",01/01/2014,January,2014
2,Midmarket,France,Carretera,None,2178.0,15.00,"32,670.00",01/06/2014,June,2014
3,Midmarket,Germany,Carretera,None,888.0,15.00,"13,320.00",01/06/2014,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,15.00,"37,050.00",01/06/2014,June,2014
...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,300.00,"631,125.00",01/03/2014,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,300.00,"139,230.00",01/10/2014,October,2014
697,Government,Mexico,Montana,High,1368.0,7.00,"8,139.60",01/02/2014,February,2014
698,Government,Canada,Paseo,High,723.0,7.00,"4,301.85",01/04/2014,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,12.00,"18,421.20",01/05/2014,May,2014

In [17]:
df_renamed["quantity"] = pd.to_numeric(df_renamed["quantity"], errors="coerce")
df_renamed["price"] = pd.to_numeric(df_renamed["price"], errors="coerce")
df_renamed

,customer_name,city,product_name,category,quantity,price,total_sales,date,month,year
0,Government,Canada,Carretera,None,1618.5,20.0,"32,370.00",01/01/2014,January,2014
1,Government,Germany,Carretera,None,1321.0,20.0,"26,420.00",01/01/2014,January,2014
2,Midmarket,France,Carretera,None,2178.0,15.0,"32,670.00",01/06/2014,June,2014
3,Midmarket,Germany,Carretera,None,888.0,15.0,"13,320.00",01/06/2014,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,15.0,"37,050.00",01/06/2014,June,2014
...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,300.0,"631,125.00",01/03/2014,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,300.0,"139,230.00",01/10/2014,October,2014
697,Government,Mexico,Montana,High,1368.0,7.0,"8,139.60",01/02/2014,February,2014
698,Government,Canada,Paseo,High,723.0,7.0,"4,301.85",01/04/2014,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,12.0,"18,421.20",01/05/2014,May,2014

In [18]:
df_renamed["total_sales"] = df_renamed["quantity"] * df_renamed["price"]

In [19]:
df_renamed["date"] = pd.to_datetime(df_renamed["date"])

In [20]:
df_renamed

,customer_name,city,product_name,category,quantity,price,total_sales,date,month,year
0,Government,Canada,Carretera,None,1618.5,20.0,32370.0,2014-01-01,January,2014
1,Government,Germany,Carretera,None,1321.0,20.0,26420.0,2014-01-01,January,2014
2,Midmarket,France,Carretera,None,2178.0,15.0,32670.0,2014-01-06,June,2014
3,Midmarket,Germany,Carretera,None,888.0,15.0,13320.0,2014-01-06,June,2014
4,Midmarket,Mexico,Carretera,None,2470.0,15.0,37050.0,2014-01-06,June,2014
...,...,...,...,...,...,...,...,...,...,...
695,Small Business,France,Amarilla,High,2475.0,300.0,742500.0,2014-01-03,March,2014
696,Small Business,Mexico,Amarilla,High,546.0,300.0,163800.0,2014-01-10,October,2014
697,Government,Mexico,Montana,High,1368.0,7.0,9576.0,2014-01-02,February,2014
698,Government,Canada,Paseo,High,723.0,7.0,5061.0,2014-01-04,April,2014
699,Channel Partners,United States of America,VTT,High,1806.0,12.0,21672.0,2014-01-05,May,2014

In [21]:
customer_data = df_renamed[['customer_name','city']]
customer_data.to_csv("customer_data.csv", index=False)

In [22]:
date_data = df_renamed[['date','month','year']]
date_data.to_csv("date_data.csv", index=False)

In [23]:
product_data = df_renamed[['product_name','category']]
product_data.to_csv("product_data.csv", index=False)

In [24]:
sales_data=df_renamed[['quantity','price','total_sales']]
sales_data.to_csv("sales_data.csv",index=False)

In [25]:
customer_data.head()

  customer_name     city
0    Government   Canada
1    Government  Germany
2     Midmarket   France
3     Midmarket  Germany
4     Midmarket   Mexico

In [26]:
import pandas as pd
import mysql.connector
import datetime 
import csv

mydb= mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales"
)

cursor=mydb.cursor()
cursor.execute("SELECT DATABASE();")
db_name=cursor.fetchone()
print(f"connected to database:{db_name[0]}")

DatabaseError: 2003 (HY000): Can't connect to MySQL server on 'localhost:3306' (10061)

In [ ]:
product_data.head()
product_data.isnull().sum()

In [ ]:
import csv
filename="product_data.csv"
with open(filename, 'r') as csvfile:
    csvread=csv.reader(csvfile)
    next(csvread)
    for row in csvread:
        product_name=row[0]
        category=row[1]
        sql = "INSERT INTO prodact_data (product_name, category) VALUES (%s, %s )"
        val = (product_name, category)
        cursor.execute(sql, val)
    



mydb.commit()
cursor.close()
mydb.close()
#print(cursor.rowcount, "record inserted.")

In [ ]:
customer_data.head()
customer_data.isnull().sum()

In [ ]:
import pandas as pd
import mysql.connector
import datetime 
import csv

mydb= mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales"
)

cursor=mydb.cursor()
cursor.execute("SELECT DATABASE();")
db_name=cursor.fetchone()
print(f"connected to database:{db_name[0]}")

filename="customer_data.csv"
with open(filename, 'r') as csvfile:
    csvread=csv.reader(csvfile)
    next(csvread)
    for row in csvread:
        customer_name=row[0]
        city=row[1]
        sql = "INSERT INTO customer_data (customer_name,city) VALUES (%s, %s )"
        val = (	customer_name,city)
        cursor.execute(sql, val)

mydb.commit()
cursor.close()
mydb.close()

In [ ]:
date_data.head()
date_data.isnull().sum()

In [ ]:
import pandas as pd
import mysql.connector
import datetime 
import csv

mydb= mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales"
)

cursor=mydb.cursor()
cursor.execute("SELECT DATABASE();")
db_name=cursor.fetchone()
print(f"connected to database:{db_name[0]}")

filename="date_data.csv"
with open(filename, 'r') as csvfile:
    csvread=csv.reader(csvfile)
    next(csvread)
    for row in csvread:
        date=row[0]
        month=row[1]
        year=row[2]
        sql = "INSERT INTO date_data (date,month,year) VALUES (%s, %s, %s )"
        val = (	date,month,year)
        cursor.execute(sql, val)

mydb.commit()
cursor.close()
mydb.close()

In [ ]:
sales_data.head()
sales_data.isnull().sum()

In [ ]:
import pandas as pd
import mysql.connector
import csv

# Connect to MySQL database
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales"
)

cursor = mydb.cursor()

# Confirm database connection
cursor.execute("SELECT DATABASE();")
db_name = cursor.fetchone()
print(f"Connected to database: {db_name[0]}")

# Open CSV file and insert data
filename = "sales_data.csv"
with open(filename, 'r', newline='', encoding='utf-8') as csvfile:
    csvread = csv.reader(csvfile)
    next(csvread)  # Skip header

    for row in csvread:
        if len(row) < 6:  # Ensure row has all required columns
            print(f"Skipping row due to missing values: {row}")
            continue

        product_id, customer_id, date_id, quantity, price, total_sales = row[:6]  # Extract first 6 columns safely

        # Check if product_id, customer_id, and date_id exist in the referenced tables
        cursor.execute("SELECT product_id FROM product_data WHERE product_id=%s", (product_id,))
        product_exists = cursor.fetchone()

        cursor.execute("SELECT customer_id FROM customer_data WHERE customer_id=%s", (customer_id,))
        customer_exists = cursor.fetchone()

        cursor.execute("SELECT date_id FROM date_data WHERE date_id=%s", (date_id,))
        date_exists = cursor.fetchone()
        

        # Insert data only if all foreign keys exist
        if product_exists and customer_exists and date_exists:
            sql = """INSERT INTO sales_data (product_id, customer_id, date_id, quantity, price, total_sales)
                     VALUES (%s, %s, %s, %s, %s, %s)"""
            val = (product_id, customer_id, date_id, quantity, price, total_sales)
            cursor.execute(sql, val)
        else:
            print(f"Skipping row due to missing foreign key references: {row}")

# Commit changes and close connections
mydb.commit()
cursor.close()
mydb.close()

In [ ]:
import pandas as pd
import mysql.connector
import csv

# Connect to MySQL database
mydb = mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales"
)

cursor = mydb.cursor()

# Confirm database connection
cursor.execute("SELECT DATABASE();")
db_name = cursor.fetchone()
print(f"Connected to database: {db_name[0]}")

# Open CSV file and insert data
filename = "sales_data.csv"
with open(filename, 'r') as csvfile:
    csvread = csv.reader(csvfile)
    next(csvread)  # Skip header

    for row in csvread:
        product_id = row[0]
        customer_id = row[1]
        date_id = row[2]
        quantity = row[3]
        price = row[4]
        total_sales = row[5]

        # Check if product_id, customer_id, and date_id exist in the referenced tables
        cursor.execute("SELECT product_id FROM product_data WHERE product_id=%s", (product_id,))
        product_exists = cursor.fetchone()

        cursor.execute("SELECT customer_id FROM customer_data WHERE customer_id=%s", (customer_id,))
        customer_exists = cursor.fetchone()

        cursor.execute("SELECT date_id FROM date_data WHERE date_id=%s", (date_id,))
        date_exists = cursor.fetchone()

        # Insert data only if all foreign keys exist
        if product_exists and customer_exists and date_exists:
            sql = """INSERT INTO sales_data (product_id, customer_id, date_id, quantity, price, total_sales)
                     VALUES (%s, %s, %s, %s, %s, %s)"""
            val = (product_id, customer_id, date_id, quantity, price, total_sales)
            cursor.execute(sql, val)

# Commit changes and close connections
mydb.commit()
cursor.close()
mydb.close()

In [ ]:
import pandas as pd
import mysql.connector
import datetime 
import csv

mydb= mysql.connector.connect(
    host="localhost",
    user="root",
    password="",
    database="sales"
)

cursor=mydb.cursor()
cursor.execute("SELECT DATABASE();")
db_name=cursor.fetchone()
print(f"connected to database:{db_name[0]}")

filename="sales_data.csv"
with open(filename, 'r') as csvfile:
    csvread=csv.reader(csvfile)
    next(csvread)
    for row in csvread:

        cursor.execute("SELECT product_id FROM prodact_data WHERE product_id=%s",(product_id,))
        cursor.execute("SELECT customer_id FROM customer_data WHERE customer_id=%s",(customer_id,))
        cursor.execute("SELECT date_id FROM date_data WHERE date_id=%s",(date_id))
        result=cursor.fetchone()
        product_id=row[0]
        customer_id=row[1]
        date_id=row[3]
        quantity=row[4]
        price=row[5]
        total_sales=row[6]
        sql = "INSERT INTO sales_data (product_id,customer_id,date_id,quantity,price,total_sales) VALUES (%s, %s, %s, %s, %s, %s )"
        val = (	date,month,year)
        cursor.execute(sql, val)

mydb.commit()
cursor.close()
mydb.close()

In [ ]:
insert_query=f" insert into cust_tb({','.join (df.columns)}) values ({','.join (['%s'] * len (df.columns))})"
for _, row in df.iterrows():
values=tuple(row)
cursor.execute(insert_query,value)
mydb.commit()